[package]
name = "twitch-stream-markers"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.14.9"
hyper-rustls = "0.22.1"
serde_json = "1.0.64"
serde = { version = "1.0.126", features = ["derive"] }
anyhow = "1.0.41"
