[package]
name = "livesplit-one"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
edition = "2018"

[features]
default = []
gl = ["gfx-backend-gl"]

[dependencies]
gfx-hal = "0.1.0"
winit = { version = "0.18.0", features = ["icon_loading"] }
gfx-backend-dx12 = "0.1.0"
gfx-backend-vulkan = "0.1.0"
gfx-backend-gl = { version = "0.1.0", optional = true }
env_logger = "0.6.0"
log = "0.4.6"
livesplit-core = { git = "https://github.com/CryZe/livesplit-core", rev = "d8cd37b957241b01ab831719112e468d02c326ca" }
# livesplit-core = { path = "livesplit-core" }
glsl-to-spirv-macros = "0.1.1"
glsl-to-spirv-macros-impl = "0.1.0"

[profile.dev]
opt-level = 1

[profile.release]
lto = true
panic = "abort"

[patch.crates-io]
gfx-hal = { git = "https://github.com/CryZe/gfx", branch = "vulkan-msaa"  }
gfx-backend-vulkan = { git = "https://github.com/CryZe/gfx", branch = "vulkan-msaa" }
gfx-backend-dx12 = { git = "https://github.com/CryZe/gfx", branch = "vulkan-msaa" }
gfx-backend-gl = { git = "https://github.com/CryZe/gfx", branch = "vulkan-msaa" }
